"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dxb3+&_nr_ptw+nhn(+qp$8*e7467g0t=xgw9@6wj@^=d-n*vu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
]

UNFOLD = {

    "SITE_TITLE": "Sudesh Bazaar Admin",

    "SITE_HEADER": "Sudesh Bazaar",

    "SITE_SUBHEADER": "E-Commerce Management",

    "SITE_SYMBOL": "shopping_cart",

    "SHOW_HISTORY": True,

    "SHOW_VIEW_ON_SITE": True,

    "SIDEBAR": {

        "show_search": True,

        "show_all_applications": True,

        "navigation": [

            {
                "title": "Store Management",

                "separator": True,

                "items": [

                    {
                        "title": "Products",
                        "icon": "inventory_2",
                        "link": "/admin/myapp/product/",
                    },

                    {
                        "title": "Categories",
                        "icon": "category",
                        "link": "/admin/myapp/category/",
                    },

                    {
                        "title": "Orders",
                        "icon": "shopping_bag",
                        "link": "/admin/myapp/order/",
                    },

                    {
                        "title": "Customers",
                        "icon": "group",
                        "link": "/admin/auth/user/",
                    },

                    {
                        "title": "Addresses",
                        "icon": "location_on",
                        "link": "/admin/myapp/address/",
                    },

                ],

            },

        ],

    },

}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myapp.context_processors.cart_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = '/login/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =========================================
# EMAIL CONFIGURATION
# =========================================

EMAIL_BACKEND = (
    'django.core.mail.backends.smtp.EmailBackend'
)

EMAIL_HOST = 'smtp.gmail.com'

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'sudeshwariv@gmail.com'

EMAIL_HOST_PASSWORD = 'nmrc bgsd phts lphf'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# =========================================
# PASSWORD RESET LINK EXPIRY
# 15 MINUTES
# =========================================

PASSWORD_RESET_TIMEOUT = 900

# =====================================
# WHATSAPP CLOUD API
# =====================================

WHATSAPP_ACCESS_TOKEN = "EAAOuZBI53Bh4BR8UZAln3UbCfzUwpSQG5ktnTVXNsRjJYZCByrtT1S0go9ZBxji09FqVxW6G6szA4bRyauQhxgZCl5i9xhAAhJB0ZCyEsdcs73hyrdDfKeAgDFRSef408sTyeHV2hxLYZCTGt5fZC8qbAnSnNj2tGZBDVYMeiKXEzulLpncIryy5uZAtRoZBAS1nHsKF7MkwgBmFc3lncA2V0MnZCf9epm697DeZCGt4A4opZAl8ZAWrAYbZB4mMTpZCqkTfqDfkTvHZCB4e7rfB4XHHquVywhZCM9C"

WHATSAPP_PHONE_NUMBER_ID = "1176763195528104"

WHATSAPP_API_VERSION = "v25.0"