# Generated by Django 5.2.14 on 2026-07-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('Changed my mind', 'Changed my mind'), ('Ordered by mistake', 'Ordered by mistake'), ('Found a better price', 'Found a better price'), ('Delivery taking too long', 'Delivery taking too long'), ('Want to change address', 'Want to change address'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
